language: node_js
node_js:
  - 10.19.0
cache:
  directories:
    - node_modules
before_script:
  - "npm i -g gatsby"
  - "npm i"
script:
  - "npm run test"
  - "(npm start & wait-on http://localhost:8000) && npm run cy:test"
  - "npm run build"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  target_branch: master
  keep_history: true
  on:
    branch: source
